       IDENTIFICATION DIVISION.
       PROGRAM-ID.    MEMRPT01.
       AUTHOR.        HCAS DEVELOPMENT TEAM.
       DATE-WRITTEN.  2024-01-15.
      *================================================================*
      * PROGRAM:  MEMRPT01                                             *
      * PURPOSE:  DAILY MEMBER ENROLLMENT ERROR AND STATISTICS REPORT  *
      *           READS THE ENROLLMENT ERROR FILE GENERATED BY THE     *
      *           NIGHTLY EDI 834 PROCESSING BATCH AND PRODUCES A      *
      *           FORMATTED PRINT REPORT FOR ENROLLMENT OPERATIONS.    *
      * INPUTS:   ENRERR-FILE  - SEQUENTIAL ERROR LOG FILE             *
      * OUTPUTS:  RPT-FILE     - FORMATTED PRINT REPORT                *
      * FREQUENCY: DAILY (POST-BATCH)                                  *
      *================================================================*
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SPECIAL-NAMES.
           C01 IS PAGE-TOP.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ENRERR-FILE
               ASSIGN TO ENRERRIN
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS WS-ENRERR-STATUS.

           SELECT RPT-FILE
               ASSIGN TO RPTOUT
               ORGANIZATION IS SEQUENTIAL
               ACCESS MODE IS SEQUENTIAL
               FILE STATUS IS WS-RPT-STATUS.

       DATA DIVISION.
       FILE SECTION.
       FD  ENRERR-FILE
           RECORDING MODE IS F
           RECORD CONTAINS 200 CHARACTERS
           BLOCK CONTAINS 0 RECORDS.
       01  ENRERR-RECORD.
           05  ERR-MEMBER-ID           PIC X(12).
           05  ERR-SUBSCRIBER-ID       PIC X(12).
           05  ERR-GROUP-ID            PIC X(10).
           05  ERR-ERROR-CODE          PIC X(04).
           05  ERR-ERROR-DESC          PIC X(60).
           05  ERR-TRANSACTION-TYPE    PIC X(02).
               88  ERR-TXN-ADD         VALUE 'AD'.
               88  ERR-TXN-CHANGE      VALUE 'CH'.
               88  ERR-TXN-TERM        VALUE 'TM'.
               88  ERR-TXN-REINSTATE   VALUE 'RI'.
           05  ERR-SEVERITY-FLAG       PIC X(01).
               88  ERR-SEV-CRITICAL    VALUE 'C'.
               88  ERR-SEV-WARNING     VALUE 'W'.
               88  ERR-SEV-INFO        VALUE 'I'.
           05  ERR-FIELD-NAME          PIC X(30).
           05  ERR-FIELD-VALUE         PIC X(30).
           05  ERR-PROCESS-DATE        PIC 9(08).
           05  ERR-SOURCE-FILE-ID      PIC X(20).
           05  FILLER                  PIC X(11).

       FD  RPT-FILE
           RECORDING MODE IS F
           RECORD CONTAINS 133 CHARACTERS
           BLOCK CONTAINS 0 RECORDS.
       01  RPT-RECORD                  PIC X(133).

       WORKING-STORAGE SECTION.

       COPY HCCOMMON.

       01  WS-FILE-STATUSES.
           05  WS-ENRERR-STATUS        PIC X(02).
           05  WS-RPT-STATUS           PIC X(02).

       01  WS-SWITCHES.
           05  WS-EOF-SW               PIC X(01) VALUE 'N'.
               88  WS-EOF              VALUE 'Y'.
               88  WS-NOT-EOF          VALUE 'N'.

       01  WS-COUNTERS.
           05  WS-TOTAL-ERRORS         PIC 9(07) VALUE ZERO.
           05  WS-CRITICAL-CNT         PIC 9(07) VALUE ZERO.
           05  WS-WARNING-CNT          PIC 9(07) VALUE ZERO.
           05  WS-INFO-CNT             PIC 9(07) VALUE ZERO.
           05  WS-ADD-ERR-CNT          PIC 9(07) VALUE ZERO.
           05  WS-CHG-ERR-CNT          PIC 9(07) VALUE ZERO.
           05  WS-TERM-ERR-CNT         PIC 9(07) VALUE ZERO.
           05  WS-REIN-ERR-CNT         PIC 9(07) VALUE ZERO.
           05  WS-LINE-COUNT           PIC 9(03) VALUE 99.
           05  WS-PAGE-COUNT           PIC 9(05) VALUE ZERO.
           05  WS-MAX-LINES            PIC 9(03) VALUE 55.

       01  WS-FORMATTED-DATE           PIC X(10).

       01  RPT-HEADER-1.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(30)
               VALUE 'NATIONAL HEALTH PARTNERS INC'.
           05  FILLER                  PIC X(35)
               VALUE SPACES.
           05  FILLER                  PIC X(28)
               VALUE 'DAILY ENROLLMENT ERROR REPT'.
           05  FILLER                  PIC X(15) VALUE SPACES.
           05  HDR1-DATE               PIC X(10).
           05  FILLER                  PIC X(04) VALUE SPACES.
           05  FILLER                  PIC X(05) VALUE 'PAGE '.
           05  HDR1-PAGE               PIC Z,ZZ9.

       01  RPT-HEADER-2.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(12) VALUE 'MEMBER ID   '.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(12) VALUE 'SUBSCRIBER  '.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(10) VALUE 'GROUP     '.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(04) VALUE 'CODE'.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(03) VALUE 'TXN'.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(03) VALUE 'SEV'.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(30) VALUE 'FIELD NAME'.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(50)
               VALUE 'ERROR DESCRIPTION'.

       01  RPT-HEADER-3.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(132) VALUE ALL '-'.

       01  RPT-DETAIL-LINE.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-MEMBER-ID           PIC X(12).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-SUBSCRIBER-ID       PIC X(12).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-GROUP-ID            PIC X(10).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-ERROR-CODE          PIC X(04).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-TXN-TYPE            PIC X(03).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-SEVERITY            PIC X(03).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-FIELD-NAME          PIC X(30).
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  DTL-ERROR-DESC          PIC X(50).

       01  RPT-SUMMARY-HDR.
           05  FILLER                  PIC X(01) VALUE SPACES.
           05  FILLER                  PIC X(40)
               VALUE '========== PROCESSING SUMMARY =========='.
           05  FILLER                  PIC X(92) VALUE SPACES.

       01  RPT-SUMMARY-LINE.
           05  FILLER                  PIC X(05) VALUE SPACES.
           05  SUM-LABEL               PIC X(35).
           05  SUM-COUNT               PIC ZZZ,ZZ9.
           05  FILLER                  PIC X(86) VALUE SPACES.

       PROCEDURE DIVISION.

       0000-MAIN-PROCESS.
           PERFORM 1000-INITIALIZE
           PERFORM 2000-PROCESS-RECORDS
               UNTIL WS-EOF
           PERFORM 3000-WRITE-SUMMARY
           PERFORM 9000-TERMINATE
           STOP RUN.

       1000-INITIALIZE.
           MOVE FUNCTION CURRENT-DATE TO WS-CURRENT-DATE
                                         WS-CURRENT-TIME
           MOVE 'MEMRPT01' TO WS-PROGRAM-ID
           STRING WS-CURR-YYYY DELIMITED SIZE
                  '/'          DELIMITED SIZE
                  WS-CURR-MM  DELIMITED SIZE
                  '/'          DELIMITED SIZE
                  WS-CURR-DD  DELIMITED SIZE
                  INTO WS-FORMATTED-DATE
           END-STRING
           OPEN INPUT  ENRERR-FILE
           IF WS-ENRERR-STATUS NOT = '00'
               DISPLAY 'MEMRPT01: ERROR OPENING INPUT FILE - FS='
                       WS-ENRERR-STATUS
               MOVE 16 TO WS-RETURN-CODE
               PERFORM 9000-TERMINATE
               STOP RUN
           END-IF
           OPEN OUTPUT RPT-FILE
           IF WS-RPT-STATUS NOT = '00'
               DISPLAY 'MEMRPT01: ERROR OPENING REPORT FILE - FS='
                       WS-RPT-STATUS
               MOVE 16 TO WS-RETURN-CODE
               PERFORM 9000-TERMINATE
               STOP RUN
           END-IF
           PERFORM 8000-READ-INPUT.

       2000-PROCESS-RECORDS.
           ADD 1 TO WS-TOTAL-ERRORS
           PERFORM 2100-TALLY-COUNTERS
           IF WS-LINE-COUNT >= WS-MAX-LINES
               PERFORM 2500-WRITE-HEADERS
           END-IF
           PERFORM 2200-FORMAT-DETAIL
           WRITE RPT-RECORD FROM RPT-DETAIL-LINE
               AFTER ADVANCING 1 LINE
           ADD 1 TO WS-LINE-COUNT
           PERFORM 8000-READ-INPUT.

       2100-TALLY-COUNTERS.
           EVALUATE TRUE
               WHEN ERR-SEV-CRITICAL
                   ADD 1 TO WS-CRITICAL-CNT
               WHEN ERR-SEV-WARNING
                   ADD 1 TO WS-WARNING-CNT
               WHEN OTHER
                   ADD 1 TO WS-INFO-CNT
           END-EVALUATE
           EVALUATE TRUE
               WHEN ERR-TXN-ADD
                   ADD 1 TO WS-ADD-ERR-CNT
               WHEN ERR-TXN-CHANGE
                   ADD 1 TO WS-CHG-ERR-CNT
               WHEN ERR-TXN-TERM
                   ADD 1 TO WS-TERM-ERR-CNT
               WHEN ERR-TXN-REINSTATE
                   ADD 1 TO WS-REIN-ERR-CNT
           END-EVALUATE.

       2200-FORMAT-DETAIL.
           INITIALIZE RPT-DETAIL-LINE
           MOVE ERR-MEMBER-ID      TO DTL-MEMBER-ID
           MOVE ERR-SUBSCRIBER-ID  TO DTL-SUBSCRIBER-ID
           MOVE ERR-GROUP-ID       TO DTL-GROUP-ID
           MOVE ERR-ERROR-CODE     TO DTL-ERROR-CODE
           MOVE ERR-TRANSACTION-TYPE TO DTL-TXN-TYPE
           EVALUATE TRUE
               WHEN ERR-SEV-CRITICAL
                   MOVE '***' TO DTL-SEVERITY
               WHEN ERR-SEV-WARNING
                   MOVE 'WRN' TO DTL-SEVERITY
               WHEN OTHER
                   MOVE 'INF' TO DTL-SEVERITY
           END-EVALUATE
           MOVE ERR-FIELD-NAME     TO DTL-FIELD-NAME
           MOVE ERR-ERROR-DESC     TO DTL-ERROR-DESC.

       2500-WRITE-HEADERS.
           ADD 1 TO WS-PAGE-COUNT
           MOVE WS-FORMATTED-DATE TO HDR1-DATE
           MOVE WS-PAGE-COUNT     TO HDR1-PAGE
           WRITE RPT-RECORD FROM RPT-HEADER-1
               AFTER ADVANCING PAGE-TOP
           WRITE RPT-RECORD FROM RPT-HEADER-2
               AFTER ADVANCING 2 LINES
           WRITE RPT-RECORD FROM RPT-HEADER-3
               AFTER ADVANCING 1 LINE
           MOVE 4 TO WS-LINE-COUNT.

       3000-WRITE-SUMMARY.
           WRITE RPT-RECORD FROM SPACES
               AFTER ADVANCING 3 LINES
           WRITE RPT-RECORD FROM RPT-SUMMARY-HDR
               AFTER ADVANCING 1 LINE
           WRITE RPT-RECORD FROM SPACES
               AFTER ADVANCING 1 LINE

           MOVE 'TOTAL ERRORS PROCESSED:'  TO SUM-LABEL
           MOVE WS-TOTAL-ERRORS            TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'CRITICAL ERRORS:'         TO SUM-LABEL
           MOVE WS-CRITICAL-CNT            TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'WARNINGS:'                TO SUM-LABEL
           MOVE WS-WARNING-CNT             TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'INFORMATIONAL:'           TO SUM-LABEL
           MOVE WS-INFO-CNT               TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           WRITE RPT-RECORD FROM SPACES
               AFTER ADVANCING 1 LINE
           MOVE 'ADD TRANSACTION ERRORS:'  TO SUM-LABEL
           MOVE WS-ADD-ERR-CNT            TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'CHANGE TRANSACTION ERRORS:' TO SUM-LABEL
           MOVE WS-CHG-ERR-CNT            TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'TERM TRANSACTION ERRORS:' TO SUM-LABEL
           MOVE WS-TERM-ERR-CNT           TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE

           MOVE 'REINSTATE TXN ERRORS:'   TO SUM-LABEL
           MOVE WS-REIN-ERR-CNT           TO SUM-COUNT
           WRITE RPT-RECORD FROM RPT-SUMMARY-LINE
               AFTER ADVANCING 1 LINE.

       8000-READ-INPUT.
           READ ENRERR-FILE
               AT END
                   SET WS-EOF TO TRUE
               NOT AT END
                   ADD 1 TO WS-RECORDS-READ
           END-READ.

       9000-TERMINATE.
           DISPLAY 'MEMRPT01: RECORDS READ    = ' WS-RECORDS-READ
           DISPLAY 'MEMRPT01: ERRORS REPORTED = ' WS-TOTAL-ERRORS
           DISPLAY 'MEMRPT01: PAGES GENERATED = ' WS-PAGE-COUNT
           CLOSE ENRERR-FILE
           CLOSE RPT-FILE
           MOVE WS-RETURN-CODE TO RETURN-CODE.
